/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by states
SELECT
    customer_state,
    COUNT(DISTINCT customer_id) AS total_customers
FROM analytic.dim_customers
GROUP BY customer_state
ORDER BY total_customers DESC;

-- Find total sellers by states
SELECT
    seller_state,
    COUNT(DISTINCT seller_id) AS total_sellers
FROM analytic.dim_sellers
GROUP BY seller_state
ORDER BY total_sellers DESC;

-- Find total products by category
SELECT
    product_category,
    COUNT(DISTINCT product_id) AS total_products
FROM analytic.dim_products
GROUP BY product_category
ORDER BY total_products DESC;

-- What is the average price in each category?
SELECT
    p.product_category,
    AVG(o.price) AS avg_price
FROM analytic.fact_orders o
INNER JOIN analytic.dim_products p
    ON o.product_key = p.product_key
GROUP BY p.product_category
ORDER BY avg_price DESC;

-- What is the total revenue generated for each category?
SELECT
    p.product_category,
    SUM(o.payment_value) AS total_revenue
FROM analytic.fact_orders o
INNER JOIN analytic.dim_products p
    ON o.product_key = p.product_key
GROUP BY p.product_category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT
    c.customer_id,
    SUM(o.payment_value) AS total_revenue
FROM analytic.fact_orders o
INNER JOIN analytic.dim_customers c
    ON o.customer_key = c.customer_key
GROUP BY c.customer_id
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across states?
SELECT
    c.customer_state,
    COUNT(*) AS total_quantity
FROM (SELECT DISTINCT order_id, order_item_id, customer_key FROM analytic.fact_orders WHERE order_item_id IS NOT NULL) t
LEFT JOIN analytic.dim_customers c
    ON t.customer_key = c.customer_key
GROUP BY c.customer_state
ORDER BY total_quantity DESC;

-- What is the distribution of sold items across states (sellers)?
SELECT
    s.seller_state,
    COUNT(*) AS total_quantity
FROM (SELECT DISTINCT order_id, order_item_id, seller_key FROM analytic.fact_orders WHERE order_item_id IS NOT NULL) t
LEFT JOIN analytic.dim_sellers s
    ON t.seller_key = s.seller_key
GROUP BY s.seller_state
ORDER BY total_quantity DESC;



